/** Milliseconds */
export const DURATION_1_SEC_MILLISECONDS = 1000;
export const DURATION_5_SECS_MILLISECONDS = DURATION_1_SEC_MILLISECONDS * 5;
export const DURATION_20_SECS_MILLISECONDS = DURATION_1_SEC_MILLISECONDS * 20;
export const DURATION_1_MIN_MILLISECONDS = DURATION_1_SEC_MILLISECONDS * 60;
export const DURATION_1_HR_MILLISECONDS = DURATION_1_MIN_MILLISECONDS * 60;
export const DURATION_1_DAY_MILLISECONDS = DURATION_1_HR_MILLISECONDS * 24;

/** Seconds */
export const DURATION_1_MIN = 1 * 60;
export const DURATION_5_MIN = DURATION_1_MIN * 5;
export const DURATION_1_HR = DURATION_1_MIN * 60;
